In [66]:
import numpy as np
import re
import pandas as pd
from scipy.spatial import distance

In [67]:
filtered_sentences = list()
with open('sentences.txt', 'r') as sentences_file:
    data = sentences_file.read()
    result = data.split('\n')
    result = [x.lower() for x in result if len(x) > 0]
    for sentence in result:
        filtered = re.split('[^a-zA-Z]', sentence)
        filtered = [x for x in filtered if len(x) > 0]
        filtered_sentences.append(filtered)
        print(filtered)

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process']
['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes']
['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output']
['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals']
['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin']
['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 't

In [68]:
uniq_words = set()
for data in filtered_sentences:
    for word in data:
        uniq_words.add(word)
uniq_words_index = list(uniq_words)
print(len(uniq_words))

254


In [69]:
sentence_vectors = np.zeros((len(filtered_sentences), len(uniq_words)))
print(sentence_vectors.shape)

(22, 254)


In [70]:
vector_index = 0
for data in filtered_sentences:
    word_dict = dict()
    for word in data:
        word_dict[word] = word_dict.get(word, 0) + 1
    for i in range(0, len(uniq_words_index)):
        sentence_vectors[vector_index, i] = word_dict.get(uniq_words_index[i], 0)
    vector_index += 1
print(sentence_vectors) 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [71]:
dt = pd.DataFrame(sentence_vectors, columns=uniq_words_index)
dt

predators  part  mice   it  received    x  left  simply  useful  more  \
0         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
1         0.0   0.0   0.0  2.0       0.0  0.0   0.0     1.0     0.0   0.0   
2         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
3         0.0   0.0   1.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
4         1.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     1.0   0.0   
5         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
6         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
7         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
8         0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
9         0.0   0.0   0.0  0.0       0.0  0.0   1.0     0.0     0.0   0.0   
10        0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
11        0.0   0.0   0.0  0.0       1.0  0.0   0.0     0.0     0.0   0.0   
12        0.0   0.0   0.0  2.0       0.0  0.0   0.0     1.0     0.0   0.0   
13        0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
14        0.0   0.0   0.0  0.0       0.0  1.0   0.0     0.0     0.0   0.0   
15        0.0   0.0   0.0  0.0       0.0  1.0   0.0     0.0     0.0   0.0   
16        0.0   0.0   0.0  0.0       0.0  2.0   0.0     0.0     0.0   0.0   
17        0.0   1.0   0.0  0.0       0.0  2.0   0.0     0.0     0.0   0.0   
18        0.0   0.0   0.0  0.0       0.0  1.0   0.0     0.0     0.0   0.0   
19        0.0   0.0   0.0  0.0       0.0  0.0   0.0     0.0     0.0   0.0   
20        0.0   0.0   0.0  0.0       0.0  1.0   0.0     0.0     0.0   0.0   
21        0.0   0.0   0.0  0.0       0.0  1.0   0.0     0.0     0.0   1.0   

    ...  factory  later  domestication  those  intel  drive  installed  \
0   ...      0.0    0.0            1.0    0.0    0.0    0.0        0.0   
1   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
2   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
3   ...      0.0    0.0            0.0    1.0    0.0    0.0        0.0   
4   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
5   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
6   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
7   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
8   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
9   ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
10  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
11  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
12  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
13  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
14  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
15  ...      1.0    0.0            0.0    0.0    0.0    0.0        1.0   
16  ...      0.0    1.0            0.0    0.0    1.0    0.0        1.0   
17  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
18  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
19  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   
20  ...      0.0    0.0            0.0    0.0    0.0    1.0        0.0   
21  ...      0.0    0.0            0.0    0.0    0.0    0.0        0.0   

    separate  online  deliberately  
0        0.0     0.0           0.0  
1        0.0     0.0           0.0  
2        0.0     0.0           0.0  
3        0.0     0.0           0.0  
4        0.0     0.0           1.0  
5        0.0     0.0           0.0  
6        0.0     0.0           0.0  
7        0.0     0.0           0.0  
8        0.0     0.0           0.0  
9        0.0     0.0           0.0  
10       0.0     0.0           0.0  
11       0.0     0.0           0.0  
12       0.0     0.0           0.0  
13       0.

In [80]:
vector_distances = list()
for i in range(0, len(sentence_vectors)):
    vector_distances.append((i, distance.cosine(sentence_vectors[0], sentence_vectors[i])))
vector_distances.sort(key=lambda x: x[1])
print(vector_distances)

[(0, 0), (6, 0.7327387580875756), (4, 0.7770887149698589), (21, 0.8250364469440588), (10, 0.8328165362273942), (12, 0.8396432548525454), (16, 0.8406361854220809), (20, 0.8427572744917122), (2, 0.8644738145642124), (13, 0.8703592552895671), (14, 0.8740118423302576), (11, 0.8804771390665607), (8, 0.8842724875284311), (19, 0.8885443574849294), (3, 0.8951715163278082), (9, 0.9055088817476932), (7, 0.9258750683338899), (5, 0.9402385695332803), (15, 0.9442721787424647), (18, 0.9442721787424647), (1, 0.9527544408738466), (17, 0.956644501523794)]


In [86]:
print("Closest vector indeces: {} and {}".format(vector_distances[1], vector_distances[2]))

Closest vector indeces: (6, 0.7327387580875756) and (4, 0.7770887149698589)
